### PR TITLE
Added extraAttributes for Slug and dusk attribute

### PR DESCRIPTION
**Pull request by CookiesEater**
Added binding of extraAttributes to Slug field and dusk attribute for both fields.

### CODE REVIEW

**Comment by wize-wiz** [comment]
@CookiesEater I believe two extra computed functions in `FormField.vue` are missing here to use the `extraAttributes` method? Or are these mixed somewhere?

```javascript
computed: {
    ...
    
    defaultAttributes() {
        return {
            placeholder: this.field.placeholder || this.field.name,
        }
    },

    extraAttributes() {
        const attrs = this.field.extraAttributes

        return {
            // Leave the default attributes even though we can now specify
            // whatever attributes we like because the old number field still
            // uses the old field attributes
            ...this.defaultAttributes,
            ...attrs,
        }
    },

    ...
}
```

**Comment by drobee** [comment]
@wize-wiz I think you're right. Nova's TextField form implementation uses the `extraAttributes` computed property on the input:
```vue
<input
    class="w-full form-control form-input form-input-bordered"
    :id="field.attribute"
    :dusk="field.attribute"
    v-model="value"
    v-bind="extraAttributes"
    :disabled="isReadonly"
/>
```

**Comment by wize-wiz** [comment]
@drobee Yea, I already implemented this feature but somehow didn't threw a PR? I also have seem to deleted the fork? All these rhetorical questions :D

`FormField` mixin doesn't implement `extraAttributes` shown here [FormField.vue](https://github.com/laravel/nova-js/blob/master/src/mixins/FormField.js). Which is actually pretty insane if you come to think to it, a simple mixin called `ExtraAttributes` would give the ability to implement this across all fields without copy/pasting functions.

You can just add the mentioned functions above to the `computed` section of `FormField.vue` (both `Slug` and `SluggableText`)  and change `v-bind="field.extraAttributes"` to `v-bind="extraAttributes"` like you wrote above.

**Comment by CookiesEater** [comment]
@wize-wiz Yes, you're right, I moved extraAttributes from directly uses to computed property

**Pull request merged**
